project/appointment/urls.py
from django.urls import path
from . import views


app_name = 'appointment'

urlpatterns = [

    
    path('appointment_list/' , views.appointment_list, name= 'appointment_list'),
    path('<int:id>/appointment_detail/', views.appointment_detail, name='appointment_detail'),
    path('add_Appointment/<int:id>/' , views.add_Appointment, name= 'add_Appointment'),
    path('appointment_list_category/<str:department>/' , views.appointment_list_category, name= 'appointment_list_category'),
    path('appointment_delete/<int:id>/', views.appointment_delete, name='appointment_delete'),
    
]

project/main_app/urls.py
from django.urls import path
from . import views
app_name = 'main_app'

urlpatterns = [


    path('' , views.home, name= 'home'),

    path('clinic_list/' , views.clinic_list, name= 'clinic_list'),
    path('<int:id>/clinic_detail/', views.clinic_detail, name='clinic_detail'),
    path('add_clinic/' , views.add_clinic, name= 'add_clinic'),
    path('clinic_delete/<int:id>/', views.clinic_delete, name='clinic_delete'),
    path("search/", views.search_page, name="search_page"),


]

project/project/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/' , include('users.urls' ,  namespace='users')),
    path('', include('main_app.urls')),
    path('appointment/', include('appointment.urls')),
]
urlpatterns += static(settings.STATIC_URL , document_root=settings.STATICFILES_DIRS) 
urlpatterns += static(settings.MEDIA_URL , document_root=settings.MEDIA_ROOT) 

project/users/urls.py
from django.urls import path
from .views import *

app_name = 'users'

urlpatterns = [
    path('signup/' , user_signup , name='signup'),
    path('login/' , user_login , name='login'),
    path('logout/' , logout , name='logout'),
]

project/appointment/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from main_app.models import Clinic


class Appointment(models.Model):
    timeAvailable = [
        ('10.00 Pm', '10.00 Pm'),
        ('10.30 Pm', '10.30 Pm'),
        ('11.00 Pm', '11.00 Pm'),
        ('11.30 Pm', '10.30 Pm'),
        ('12.00 Pm', '12.00 Pm'),
        ('12.30 Pm', '12.30 Pm'),
        ('1.00 Pm', '1.00 Pm'),
        ('1.30 Pm', '1.30 Pm'),
        ('2.00 Pm', '2.00 Pm'),
        ('2.30 Pm', '2.30 Pm'),
        ('3.00 Pm', '3.00 Pm'),
        ('3.30 Pm', '3.30 Pm'),
        ('4.00 Pm', '4.00 Pm'),
        ('4.30 Pm', '4.30 Pm'),
        ('5.00 Pm', '5.00 Pm'),
        ('5.30 Pm', '5.30 Pm'),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    clinic = models.ForeignKey(Clinic, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    patient_age = models.IntegerField()
    discription = models.TextField(max_length=500)
    phone_number = models.CharField(max_length=120)
    appointment_datetime = models.CharField(choices=timeAvailable, max_length=30, unique=True)
    is_attended = models.BooleanField(default=False)
    is_available = models.BooleanField(default=True)  


    def __str__(self):
        return self.name

project/main_app/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class Clinic(models.Model):
    department = (
    ('Heart Center', "Heart Center"),
    ('Neuroscience Center', "Neuroscience Center"),
    ('Obesity Center', "Obesity Center"),
    ('Orthopedic Center', 'Orthopedic Center'),
    ('Pediatric Center', 'Pediatric Center'),
    ('Eye Center', 'Eye Center'),
)

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    doctor_name = models.CharField(max_length=100)
    feature_image = models.ImageField()
    discription = models.TextField(max_length=500)
    department = models.CharField(choices=department, max_length=100)
    established_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name

project/main_app/forms.py
from django import forms
from .models import Clinic


class ClinicForm(forms.ModelForm):

    class Meta:
        model = Clinic
        fields = ("name" ,"feature_image","discription","department" ,)
        
        

project/main_app/views.py
from .models import *
from django.shortcuts import render
from django.http import HttpRequest, HttpResponse
from django.shortcuts import redirect, render
from django.shortcuts import render, get_object_or_404, redirect

from django.contrib.auth.decorators import login_required
from .forms import ClinicForm



@login_required
def home(request):
    clinic_list  = Clinic.objects.all()


    return render(request ,'home.html', {
        'clinic_list' : clinic_list ,

    })


@login_required
def clinic_list(request):
    clinic_list  = Clinic.objects.all()

    return render(request ,'my_clinic_list.html', {
        'clinic_list' : clinic_list ,

    })
    
@login_required 
def clinic_detail(request , id):
    clinic_detail  = get_object_or_404(Clinic, id=id)

    return render(request ,'clinic_detail.html', {
        'clinic_detail' : clinic_detail ,

    })
    
@login_required 
def add_clinic(request):
    clinic_form = ClinicForm(request.POST or None , request.FILES)
    if request.method == 'POST':
        clinic_form = ClinicForm(request.POST or None , request.FILES)
        if clinic_form.is_valid():
            check_user_request = clinic_form.save(commit=False)
            check_user_request.user = request.user
            check_user_request.save()
            return redirect('main_app:home')

    else:
        clinic_form = ClinicForm()
    return render(request ,'add_clinic.html', {
        'clinic_form' : clinic_form ,
    })
    

    
    
@login_required
def clinic_delete(request , pk):
    clinic_delete = Clinic.objects.get(pk=pk)
    clinic_delete.delete()


def search_page(request:HttpRequest):
    
    search_phrase = request.GET.get("query", "")
    clinics = Clinic.objects.filter(department__contains=search_phrase)

    return render(request, "search_page.html", {"clinics" : clinics})

project/main_app/templates/add_clinic.html
{% extends 'main_app/home.html' %}
{%load static%}
{% load bootstrap4 %}



{%block content%}
            <section class="banner-section d-flex justify-content-center align-items-end">
                <div class="section-overlay"></div>

                <div class="container">
                    <div class="row">

                        <div class="col-lg-7 col-12">
                            <h1 class="text-white mb-lg-0">Add</h1>
                        </div>

                        <div class="col-lg-4 col-12 d-flex justify-content-lg-end align-items-center ms-auto">
                            <nav aria-label="breadcrumb">
                                <ol class="breadcrumb justify-content-center">
                                    <li class="breadcrumb-item"><a href="index.html">Home</a></li>

                                    <li class="breadcrumb-item active" aria-current="page">Add</li>
                                </ol>
                            </nav>
                        </div>

                    </div>
                </div>
            </section>


            <section class="contact-section section-padding">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-6 col-12">
                            <form class="custom-form consulting-form bg-white shadow-lg mb-5 mb-lg-0" action="#" method="POST" role="form" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="consulting-form-header d-flex align-items-center">
                                    <h3 class="mb-4">Add a New Painting</h3>
                                </div>
                                         {% bootstrap_form clinic_form %}
                                    <div class="col-lg-6 col-md-10 col-8 mx-auto">
                                        <button type="submit" class="form-control">Add</button>
                                    </div>
                                </div>
                            </form>
                        </div>

                    </div>
                </div>
            </section>
        </main>
        {%endblock%}

project/main_app/templates/clinic_detail.html
{% extends 'main_app/home.html' %}
{%load static%}


{%block content%}
<style>
      h2{color: #333;text-align: center;text-transform: uppercase;font-family: "Roboto", sans-serif;font-weight: bold;position: relative;margin: 25px 0 50px}h2::after{content: "";width: 100px;position: absolute;margin: 0 auto;height: 3px;background: #ffdc12;left: 0;right: 0;bottom: -10px}.carousel{width: 650px;margin: 0 auto;padding-bottom: 50px}.carousel .item{color: #999;font-size: 14px;text-align: center;overflow: hidden;min-height: 340px}.carousel .item a{color: #eb7245}.carousel .img-box{width: 145px;height: 145px;margin: 0 auto;border-radius: 50%}.carousel .img-box img{width: 100%;height: 100%;display: block;border-radius: 50%}.carousel .testimonial{padding: 30px 0 10px}.testimonial{color: #000000;font:Times Roman}.carousel .overview{text-align: center;padding-bottom: 5px}.carousel .overview b{color: #333;font-size: 15px;text-transform: uppercase;display: block;padding-bottom: 5px}.carousel .star-rating i{font-size: 18px;color: #ffdc12}.carousel .carousel-control{width: 30px;height: 30px;border-radius: 50%;background: #999;text-shadow: none;top: 4px}.carousel-control i{font-size: 20px;margin-right: 2px}.carousel-control.left{left: auto;right: 40px}.carousel-control.right i{margin-right: -2px}.carousel .carousel-indicators{bottom: 15px}.carousel-indicators li, .carousel-indicators li.active{width: 11px;height: 11px;margin: 1px 5px;border-radius: 50%}.carousel-indicators li{background: #e2e2e2;border-color: transparent}.carousel-indicators li.active{border: none;background: #888}

</style>

            <section class="banner-section d-flex justify-content-center align-items-end">
                <div class="section-overlay"></div>

                <div class="container">
                    <div class="row">

                        <div class="col-lg-7 col-12">
                            <h1 class="text-white mb-lg-0">  {{clinic_detail.name}} </h1>
                        </div>

                        <div class="col-lg-4 col-12 d-flex justify-content-lg-end align-items-center ms-auto">
                            <nav aria-label="breadcrumb">
                                <ol class="breadcrumb justify-content-center">
                                    <li class="breadcrumb-item"><a href="index.html">Home</a></li>

                                    <li class="breadcrumb-item active" aria-current="page">Details</li>
                                </ol>
                            </nav>
                        </div>

                    </div>
                </div>
            </section>

            <div class="table-wrapper">
                <div id="myCarousel" class="carousel slide" data-ride="carousel">
                    <!-- Carousel indicators -->
                    <ol class="carousel-indicators">
                        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                        <li data-target="#myCarousel" data-slide-to="1"></li>
                        <li data-target="#myCarousel" data-slide-to="2"></li>
                    </ol> <!-- Wrapper for carousel items -->
                    <div class="carousel-inner">
                        
                        <div class="item carousel-item active">
                            <br>
                     
                            <div  class="img-box"><img src="{{clinic_detail.feature_image.url}}" alt=""></div>
                            <br>
                            
                            <p class="overview"><b> {{clinic_detail.name}} </b>Creates at:{{clinic_detail.established_at|date:"F j, Y"}} </p>
                            <p class="testimonial">{{clinic_detail.discription}}</p>
                            <p class="overview"><b>Department name{{clinic_detail.department}}</b> </p>
                            <p class="overview"><b>Doctor name{{clinic_detail.doctor_name}}</b> </p>
                            <div class="star-rating"> 
                                <li class="material-symbols-outlined"><a href="">arrow_right_alt</a></li>
                            </div>
                            {% if  perms.appointment.change_appointment and perms.appointment.delete_appointment %}

                            <a  class="btn btn-outline-success"  style="width: 200px; height: 15;" href="{% url 'appointment:appointment_list' %}">
                             All appointment
                            </a>
                            {% else %}
                            <a class="btn btn-outline-success"  style="width: 200px; height: 15;" href="{% url 'appointment:add_Appointment' clinic_detail.id %}">
                             Book Appointment
                            </a>
                            {% endif %}

                        </div>
                       
                    </div> 
                    </a>
                </div> 
              </div>
        </main>
        {%endblock%}
         

project/main_app/templates/search_page.html
{% extends 'main_app/home.html' %}
{%load static%}

{%block content%}



<br>
         

          

            <section class="services-section section-padding section-bg" id="services-section">



                            
{% block clinic %}
<div class="container-fluid">
    <main class="tm-main">
        <!-- Search form -->
        <div class="row tm-row">
            <div class="col-12">
     

                    <h3>Search results for <span class="text-success">{{request.GET.query}}</span></h3>                                           
                
            </div>                
        </div>      
      
       
       
        <div class="row tm-row">
            <div class="col-12">
                <form  action="{% url 'main_app:search_page'%}" role="search"  method="GET" class="form-inline tm-mb-80 tm-search-form">                
                    <input class="form-control tm-search-input" name="query" type="text" placeholder="Search..." aria-label="Search">
                                             
                </form>
            </div>                
        </div>            
    


        <div class="col-lg-12 col-12">
            <h2 class="mb-4">Our Clinics</h2>
        </div>
        {% for clinic in clinics %}
            <div class="col-lg-6 col-12">
                <div class="services-thumb">
                    <div class="row">
                        <div class="col-lg-5 col-md-5 col-12">
                            <div class="services-image-wrap">
                                <a href="#">
                                    {% if clinic.feature_image %}
                                    <img src="{{clinic.feature_image.url}}" class="services-image img-fluid" alt="">
                                   {% else %}
                                   <img src="" class="services-image img-fluid" alt="">

                                    {% endif %}
                                    <div class="services-icon-wrap">
                                        <div class="d-flex justify-content-between align-items-center">
                                            <p class="text-white mb-0">
                                                <i></i>
                                            
                                            </p>

                                            <p class="text-white mb-0">
                                                <i></i>
                                            
                                            </p>
                                        </div>
                                    </div>
                                </a>
                            </div>
                        </div>

                        <div class="col-lg-7 col-md-7 col-12 d-flex align-items-center">
                            <div class="services-info mt-4 mt-lg-0 mt-md-0">
                                <h4 class="services-title mb-1 mb-lg-2">
                                    <a class="services-title-link" href="#">{{clinic.department}}</a>
                                </h4>

                                <p>{{clinic.discription}}</p>

                                <div class="d-flex flex-wrap align-items-center">
                                    <div class="reviews-icons">
                                        <i class="bi-star-fill"></i>
                                        <i class="bi-star-fill"></i>
                                        <i class="bi-star-fill"></i>
                                        <i class="bi-star-fill"></i>
                                        <i class="bi-star-fill"></i>
                                    </div>
            

                                    <a href="{% url 'main_app:clinic_detail' clinic.id %}" class="custom-btn btn button button--atlas mt-2 ms-auto">
                                        <span>Read More</span>

                                        
                                    </a>
                                    <a href="{% url 'appointment:appointment_list_category' clinic.department %}" class="custom-btn btn button button--atlas mt-2 ms-auto">
                                        <span>All Appointments</span>

                                        
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
     


    </div>
</div>
</section>

{%endblock%}
                       
                    </div> 
                    </a>
                </div> 
              </div>
        </main>
        {%endblock%}
         