Hospital/Hospital/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('', include('clinic_app.urls')),
    path("admin/", admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Hospital/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('signin/', views.signin, name="sign_in"),
    path('signup/', views.signup, name="signup"),
    path('user/logout/', views.logout_view, name="log_out"),
]

Hospital/clinic_app/urls.py
from django.urls import path
from . import views

app_name = "clinic_app"

urlpatterns = [
    path("", views.home, name = "home"),
    path('add/clinic', views.add_clinic, name='add_clinic'),
    path('clinic/details/<clinic_id>/', views.clinic_details, name='clinic_details'),
    path("search/", views.search, name="search"),
    path("update/clinic/<clinic_id>/", views.update_clinic, name="update_clinic"),
    path("contact/", views.contact, name="contact"),
    path("appointment/<clinic_id>/", views.appointment_page, name="appointment"),
    path('create/appointment/<clinic_id>/', views.create_appointment, name='create_appointment'),
    path('not/found/', views.not_found, name="not_found"),
    path('update/appointment/<appointment_id>', views.update_appointment, name="update_appointment"),
    path('delete/appointment/<appointment_id>', views.delete_appointment, name="delete_appointment"),

]

Hospital/main_app/urls.py
from django.urls import path
from . import views

app_name = "main_app"

urlpatterns = [
    path("", views.index_page, name="index_page"),
    path("add/clinic",views.add_clinic,name="add_clinic"),
    path("clinics/details/<clinic_id>/", views.clinic_detail, name="clinic_detail"),
    path("clinics/appointment/add/<clinic_id>/", views.make_appointment, name="make_appointment"),
    path("clinics/search/", views.search_page, name="search_page"),
    path('clinics/update/<clinic_id>',views.update_clinic,name="update_clinic"),
    path("clinics/delete/<clinic_id>/", views.delete_clinic, name="delete_clinic"),
    path("appointment/all/",views.appointment_view,name="appointment_view"),
]

Hospital/users_app/urls.py
from django.urls import path
from . import views

app_name = "users_app"

urlpatterns = [
    path('signup/', views.signup, name = 'signup'),

    path('signin/', views.signin, name = 'signin'),

    path('signout/', views.signout, name = 'signout'),

    path('permission_page/', views.no_permission, name = 'no_permission')
]

Hospital/main_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

DEP_CHOICES = (
    ('HC', 'Heart Center'),
    ('EUC', 'euroscience Center'),
    ('OBC', 'Obesity Center'),
    ('EYEC', 'Eye Center'),
    ('ORC', 'Orthopedic Center'),
    ('PEC', 'Pediatric Center'),
)

class Clinic(models.Model):
    name = models.CharField(max_length=200)
    feature_image = models.ImageField(upload_to="images/", default="images/default.jpg")
    description = models.TextField()
    department = models.CharField(max_length =100, choices = DEP_CHOICES)
    established_at = models.DateField(auto_now_add=True)
    def __str__(self) -> str:
        return f"{self.name}"

    

class Appointment(models.Model):
    clinic = models.ForeignKey(Clinic, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    case_description = models.TextField()
    patient_age = models.IntegerField()
    appointment_datetime = models.DateTimeField()
    is_attended = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.user.username}"

Hospital/main_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpRequest, HttpResponse
from .models import Clinic,Appointment

# Create your views here.

def index_page(request:HttpRequest):

    if request.user.is_authenticated:
        print(request.user.first_name)

    clinics = Clinic.objects.all()

    return render(request, "main_app/index.html", {"clinics" : clinics})



def add_clinic(request:HttpRequest):

    if not request.user.is_staff:
        return redirect("accounts:no_permission_page")

    if request.method == "POST":
        #addin a new clinic in database
        new_clinic = Clinic(name=request.POST["name"], description=request.POST["description"], department=request.POST["department"], feature_image=request.FILES["feature_image"])
        new_clinic.save()
        return redirect("main_app:index_page")

    return render(request, "main_app/add_clinic.html")



def update_clinic(request:HttpRequest, clinic_id):
    if not (request.user.has_perm("main_app.change_clinic")):
        return redirect("accounts:no_permission_page")
    
    clinic = Clinic.objects.get(id=clinic_id)

    #updating the clinic
    if request.method == "POST":
        clinic.name = request.POST["name"]
        clinic.description = request.POST["description"]
        clinic.department = request.POST["department"]
        clinic.established_at = request.POST["established_at"]

        if "feature_image" in request.FILES:
            clinic.feature_image = request.FILES["feature_image"]
        clinic.save()

        return redirect("main_app:clinic_detail", clinic_id=clinic.id)

    return render(request, 'main_app/update_clinic.html', {"clinic" : clinic})



def delete_clinic(request:HttpRequest, clinic_id):

    #check that user is staff and has a permission to delete
    if not (request.user.is_staff and  request.user.has_perm("main_app.delete_clinic")):
        return redirect("accounts:no_permission_page")
    
    clinic = Clinic.objects.get(id=clinic_id)
    clinic.delete()

    return redirect("main_app:index_page")



def clinic_detail(request:HttpRequest, clinic_id):

    try:
        clinic = Clinic.objects.get(id=clinic_id)
    except:
        return render(request, 'main_app/not_found.html')

    return render(request, 'main_app/clinic_detail.html', {"clinic" : clinic})


def make_appointment(request:HttpRequest, clinic_id):

    if request.method == "POST":
        clinic_object = Clinic.objects.get(id=clinic_id)
        new_appointment = Appointment(clinic=clinic_object, user=request.user, case_description=request.POST["case_description"], patient_age=int(request.POST["patient_age"]),appointment_datetime=request.POST["appointment_datetime"]) 
        new_appointment.save()
        return redirect("main_app:clinic_detail",clinic_id=clinic_object.id)
    
    return render(request,"main_app/clinic_detail.html")



def appointment_view(request:HttpRequest):

    if not (request.user.is_staff and  request.user.has_perm("main_app.add_appointment")):
        appointments=Appointment.objects.filter(user=request.user)
    else:
        appointments=Appointment.objects.all()
    return render(request,"main_app/appointment_view.html",{"appointments":appointments })


def search_page(request:HttpRequest):
    search_phrase = request.GET.get("search", "")
    clinics = Clinic.objects.filter(name__contains=search_phrase)

    return render(request, "main_app/search_page.html", {"clinics" : clinics})





    

Hospital/main_app/templates/main_app/add_clinic.html
{% extends 'main_app/index.html' %}

{% block title %} Add New Clinic {% endblock%}


{% block content %}

<div class="container">
        <form action="" method="POST" enctype="multipart/form-data"> 
            {% csrf_token %}
            <div class="mb-3">
                <label for="exampleFormControlInput1" class="form-label">Name</label>
                <input type="text" class="form-control" id="exampleFormControlInput1" placeholder="clinic name" name="name">
            </div>
    
            <div class="mb-3">
                <label for="exampleFormControlInput1" class="form-label">Description</label>
                <textarea class="form-control" id="exampleFormControlInput1" placeholder="clinic description" name="description"></textarea>
            </div>
    
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                  <label class="input-group-text" for="inputGroupSelect01">Department</label>
                </div>
                <select class="custom-select" id="inputGroupSelect01" name="department">
                    <option selected>Choose the department...</option>
                    <option value="HC">Heart Center</option>
                    <option value="EUC">euroscience Center</option>
                    <option value="OBC">Obesity Center</option>
                    <option value="EYEC">Eye Center</option>
                    <option value="ORC">Orthopedic Center</option>
                    <option value="PEC">Pediatric Center</option>
                </select>
                </select>
            </div>
            
            <div class="mb-3">
              <label for="exampleFormControlInput1" class="form-label">Choose Image</label>
              <input type="file" name="feature_image" class="form-control" />
            </div>
    
            <div class="mb-3">
                <input type="submit" value="Add Post" class="btn btn-primary" />
            </div>
        </form>
        {% endblock %}
    </div>
    

Hospital/main_app/templates/main_app/appointments.html
{% extends 'main_app/base.html' %}

{% load static %}

{% block content %}
<h2>Appointments</h2>
    <div class="container" style="display: flex;">
            {% for appointment in appointment %}
                <ul class="row">
                    <p>{{ appointment.clinic.name }}</p>
                    <p>{{ appointment.clinic.department }}</p>
                    <p>{{ appointment.id }}</p>
                    <p>{{ appointment.user.username }}</p>
                    <p>{{ appointment.case_description }}</p>
                    <p>{{ appointment.patient_age }}</p>
                    <p>{{ appointment.appointment_datetime|date }}</p>
                    <p>{{ appointment.appointment_datetime|time }}</p>
                    {% if appointment.is_attended %}
                        <p>Present</p>
                    {% else %}
                        <p>Absent</p>
                    {% endif %}
                    <div>
                        <a href="{% url 'main_app:appointments_update' appointment.id %}" class="btn btn-warning">Update</a>
                    </div>
                    <div>
                        <a href="{% url 'main_app:appointments_delete' appointment.id %}" class="btn btn-danger">Delete</a>
                    </div>
                </ul>
            {% endfor %}
        </div>
    </div>
{% endblock %}

Hospital/main_app/templates/main_app/appointments_add.html
{% extends 'main_app/base.html' %}
{% load static %}

{% block content %}
    <div class="container">
        <div class="d-flex align-items-center">
            
                <div class="container mb-5">
                    <form action="{% url 'main_app:appointments_add' %}" method="POST" class="align-items-center justify-content-center">
                        {% csrf_token %}
                        <h1>Add Appointment</h1>

                        <label for="exampleFormControlInput1" class="form-label">Name</label>
                        <select name="user" class="form-select" aria-label="Default select example">
                            <option selected>Name</option>
                            {% for user in user %}
                                <option value="{{user.id}}">{{user.username}}</option>
                            {% endfor %}
                        </select>

                        <label for="exampleFormControlInput1" class="form-label">Age:</label>
                        <select name="patient_age" class="form-select" aria-label="Default select example">
                            <option selected>Age</option>
                            {% for i  in age %}
                                <option value="{{i}}">{{i}}</option>
                            {% endfor %}
                        </select>

                        <label for="exampleFormControlInput1" class="form-label">Clinic:</label>
                        <select name="clinic" class="form-select" aria-label="Default select example">
                            <option selected>clinic</option>
                            {% for clinic in clinic %}
                                <option value="{{clinic.id}}">{{clinic.name}}</option>
                            {% endfor %}
                        </select>

                        <div class="mb-3">
                            <span class="input-group-text">Description:</span>
                            <textarea class="form-control" name="case_description" aria-label="With textarea"></textarea>
                        </div>

                        <div class="mb-3">
                            <label for="exampleFormControlInput1" class="form-label">Date:</label>
                            <input type="date" name="date"/>
                        </div>

                        <div class="mb-3">
                            <label for="exampleFormControlInput1" class="form-label">Time:</label>
                            <input type="time" name="time" />
                        </div>
                        <br>

                        <button class="btn btn-primary" type="submit" >Add</button>
                    </form>
                </div>
          
        </div>
    </div>
{% endblock %}

Hospital/main_app/templates/main_app/appointments_update.html
{% extends 'main_app/base.html' %}
{% load static %}

{% block content %}
    <div class="container">
        <div class="d-flex align-items-center">
                <div class="container mb-5">
                    <form action="{% url 'main_app:appointments_update' appointment.id %}" method="POST" class="align-items-center justify-content-center">
                        {% csrf_token %}
                        <h1 class="mb-3">Update {{appointment.user.username}} Appointment</h1>

                        <div class="mb-3">
                            <span class="input-group-text">Description</span>
                            <textarea class="form-control" name="case_description" aria-label="With textarea">{{appointment.case_description}}</textarea>
                        </div>

                        <div class="mb-3">
                            <label for="exampleFormControlInput1" class="form-label">Date</label>
                            <input type="date" name="date" value="date" />
                        </div>

                        <div class="mb-3">
                            <label for="exampleFormControlInput1" class="form-label">Time:</label>
                            <input type="time" name="time" value="time" />
                        </div>

                        <div class="form-check">
                            <input name="is_attended" class="form-check-input" type="radio" value="True" id="flexCheckDefault" {% if appointment.is_attended == True %} checked {% endif %}>
                            <label class="form-check-label" for="flexCheckDefault">
                                Present
                            </label>
                        </div>
                        <div class="form-check">
                            <input name="is_attended" class="form-check-input" type="radio" value="False" id="flexCheckChecked" {% if appointment.is_attended == False %} checked {% endif %}>
                            <label class="form-check-label" for="flexCheckChecked">
                                Absent
                            </label>
                        </div>
                        <br>

                        <button class="btn btn-primary" type="submit">Update</button>
                    </form>
                </div>
        </div>
    </div>
{% endblock %}

Hospital/main_app/templates/main_app/base.html
{% load static %}
        
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="keywords" content="">
        <meta name="author" content="Tooplate">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/animate.css' %}">
        <link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}">
        <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
        <title>Hospital</title>
        

     <!-- MAIN CSS -->
     <link rel="stylesheet" href="{% static 'css/tooplate-style.css' %}">

</head>
<body id="top" data-spy="scroll" data-target=".navbar-collapse" data-offset="50">

     <!-- HEADER -->
     <header>
          <div class="container">
              <div class="row">
                <div class="col-md-4 col-sm-5">
                     <p>Welcome to a Professional Health Care</p>
                </div>     
                <div class="col-md-8 col-sm-7 text-align-right">
                     <span class="phone-icon"><i class="fa fa-phone"></i> 011-066-5456</span>
                     <span class="date-icon"><i class="fa fa-calendar-plus-o"></i> 6:00 AM - 10:00 PM (Sun-Thur)</span>
                     <span class="email-icon"><i class="fa fa-envelope-o"></i> <a href="#">info@company.com</a></span>
                </div
              </div>
          </div>
     </header>


      <section class="navbar navbar-default navbar-static-top" role="navigation">
          <div class="container">

               <div class="navbar-header">
                    <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                         <span class="icon icon-bar"></span>
                         <span class="icon icon-bar"></span>
                         <span class="icon icon-bar"></span>
                    </button>

                    <!-- lOGO TEXT HERE -->
                    <a href="{% url 'main_app:home' %}" class="navbar-brand"><i class="fa fa-h-square"></i>ealth Center</a>
               </div>

               <!-- MENU LINKS -->
              <div class="collapse navbar-collapse" style="display: flex;">
                <ul class="nav navbar-nav mx-auto">
                    <li><a href="{% url 'main_app:home' %}" class="nav-link smoothScroll">Home</a></li>
                    <li><a href="{% url 'main_app:clinics' %}" class="nav-link smoothScroll">Clinics</a></li>
                    {% if request.user.is_staff %}
                        <li><a href="{% url 'main_app:manager' %}" class="nav-link smoothScroll">Manager</a></li>
                        <li><a href="{% url 'main_app:manager_add' %}" class="nav-link px-2">Add Clinics</a></li>
                        <li><a href="{% url 'main_app:manager_appointments' %}" class="nav-link px-2">Appointmints</a></li>
                        <li><a href="{% url 'main_app:appointments_add' %}" class="nav-link px-2">Add Appointmint</a></li>
                    {% endif %}
                </ul>
            
                {% if request.user.is_authenticated %}
                    <div class="navbar-right mx-auto">
                        <h5 class="mb-3">Welcome, {{ request.user.username }}</h5>
                        <a href="{% url 'users_app:signout' %}" class="btn btn-danger">Sign Out</a>
                    </div>
                {% else %}
                    <div class="navbar-right ml-auto">
                        <a href="{% url 'users_app:signup' %}" class="btn btn-warning">Sign Up</a>
                        <a href="{% url 'users_app:signin' %}" class="btn btn-primary">Sign in</a>
                    </div>
                {% endif %}
              </div>
            

          </div>
      </section>
      
     <!-- HOME -->
     <section id="home" class="slider" data-stellar-background-ratio="0.5">
      <div class="container">
          <div class="row">
              <div class="owl-carousel owl-theme">
                  <div class="item item-first">
                      <div class="caption">
                          <div class="col-md-offset-1 col-md-10">
                              <!-- Hero Image -->
                              <img src="{% static 'images/about-bg.jpg' %}" alt="Hero Image" class="img-fluid">
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
  </section>
  
    

     <!-- ABOUT -->
  <section id="about">
    <div class="container">
           <div class="row">

                <div class="col-md-6 col-sm-6">
                     <div class="about-info">
                          <h2 class="wow fadeInUp" data-wow-delay="0.6s">Welcome to Your <i class="fa fa-h-square"></i>ealth Center</h2>
                          <div class="wow fadeInUp" data-wow-delay="0.8s">
                               <p>Healthcare.</p>
                               <p>Below You'll find our clinics.</p>
                          </div>                          
                     </div>
                </div>
              
           </div>
      </div>
  </section>

  <section id="team" data-stellar-background-ratio="1">
    <div class="container">
        <div class="row">
              <div class="col-md-6 col-sm-6">
                   <div class="about-info">
                        <h2 class="wow fadeInUp" data-wow-delay="0.1s">Our Clinics</h2>
                   </div>
              </div>

              <div class="clearfix"></div>
      </div>
  </section>
  {% block content %}
                       
  {% endblock %}


  <footer data-stellar-background-ratio="5">
          <div class="container">
               <div class="row">

                    <div class="col-md-6">
                         <div class="footer-thumb"> 
                              <h4 class="wow fadeInUp" data-wow-delay="0.4s">Contact Info</h4>
                              <div class="contact-info">
                                   <p><i class="fa fa-phone"></i>  011-066-5456</p>
                                   <p><i class="fa fa-envelope-o"></i> <a href="#">info@company.com</a></p>
                              </div>
                         </div>
                    </div>
                    <div class="col-md-6"> 
                         <div class="footer-thumb">
                              <div class="opening-hours">
                                   <h4 class="wow fadeInUp" data-wow-delay="0.4s">Opening Hours</h4>
                                   <p>Sunday - Thursday <span>06:00 AM - 10:00 PM</span></p>
                                   <p>Saturday <span>09:00 AM - 08:00 PM</span></p>
                                   <p>Friday <span>Closed</span></p>
                              </div> 

                          </div>
                    </div>
               </div>
          </div>
     </footer>

     <!-- SCRIPTS -->
     <script src="{% static 'js/jquery.js' %}"></script>
     <script src="{% static 'js/bootstrap.min.js' %}"></script>
     <script src="{% static 'js/jquery.sticky.js' %}"></script>
     <script src="{% static 'js/jquery.stellar.min.js' %}"></script>
     <script src="{% static 'js/wow.min.js' %}"></script>
     <script src="{% static 'js/smoothscroll.js' %}"></script>
     <script src="{% static 'js/owl.carousel.min.js' %}"></script>
     <script src="{% static 'js/custom.js' %]"></script>

    

Hospital/main_app/templates/main_app/clinic_detail.html
{% extends 'main_app/index.html' %}

{% block title %} Clinic Details {% endblock%}


{% block content %}

<div class="container d-flex flex-column gap-2 align-items-center ">
  <h1>{{clinic.name}}</h1>
  <img class="rounded-5" src="{{clinic.feature_image.url}}" style="width:15cm ;height:12cm; border-radius: 3px;"/>
  <div class="d-flex justify-content-between align-items-center gap-2">
    <div class="d-flex gap-2">
      {% if perms.main_app.change_clinic and perms.main_app.delete_clinic%}
      <a href="{% url 'main_app:update_clinic' clinic.id %}" class="btn btn-warning">update game</a>
      <a href="{% url 'main_app:delete_clinic' clinic.id %}" class="btn btn-danger">Delete game</a>
      {% endif %}
    </div>
  </div>
  <p>{{clinic.description}}</p>
</div>

<!-- Make Appointment -->
{% if request.user.is_authenticated %}
<div class="page-section">
  <div class="container">
    <h1 class="text-center wow fadeInUp">Make an Appointment</h1>
    
    <form class="main-form" method="post" action="{% url 'main_app:make_appointment' clinic.id %}"> 
      {% csrf_token %}
      <div class="row mt-5 ">
        <div class="col-12 col-sm-6 py-2 wow fadeInRight">
          <input type="text" class="form-control" placeholder="Your age.." name="patient_age">
        </div>
        <div class="col-12 col-sm-6 py-2 wow fadeInLeft" data-wow-delay="300ms">
          <input type="date" class="form-control" name="appointment_datetime" placeholder="Choose Date:">
        </div>
        <!-- <div class="col-12 py-2 wow fadeInUp" data-wow-delay="300ms">
          <input type="text" class="form-control" placeholder="yout..">
        </div> -->
        <div class="col-12 py-2 wow fadeInUp" data-wow-delay="300ms">
          <textarea name="case_description" id="message" class="form-control" rows="6" placeholder="Enter your case description.."></textarea>
        </div>
      </div>
      <button type="submit" class="btn btn-primary mt-3 wow zoomIn">Booking</button>
    </form>
  </div>
  {% else %}
  <div class="alert alert-dark" role="alert">
    Please <a href="{% url 'accounts:sign_up' %}">register</a> or <a href="{% url 'accounts:sign_in' %}">log in</a> to booking an appointment!
  </div>
  {% endif %}
  
  {% endblock %}
</div>

  

Hospital/main_app/templates/main_app/clinics.html
{% extends 'main_app/base.html' %}
{% load static %}

{% block content %}
    <div class="container">
        <nav class="navbar">
            <div class="container-fluid">
                <form action="{% url 'main_app:search' %}" method="GET" class="d-flex" role="search">
                    <input name="search" class="form-control" type="search" placeholder="Clinics" aria-label="Search">
                    <button class="btn btn-outline" type="submit">Search</button>
                </form>
            </div>
          </nav>
    </div>
    <div class="container mb-5">
        <div class="row">
          <div class="col-12">
            <div class="card-deck">
              {% for clinic in clinic %}
              <div class="card">
                <img src="{{ clinic.feature_image.url }}" class="card-img-top" alt="Clinic Image" style="object-fit: cover; height: 200px;">
                <div class="card-body">
                  <h5 class="card-title">{{ clinic.name }}</h5>
                  <p class="card-text">{{ clinic.description }}</p>
                </div>
                <div class="card-footer">
                  <a href="{% url 'main_app:clinics_detail' clinic.id %}" class="btn btn-primary">View More</a>
                </div>
              </div>
              {% endfor %}
            </div>
          </div>
        </div>
      </div>
{% endblock %}

Hospital/main_app/templates/main_app/home.html
{% extends 'main_app/base.html' %}
{% load static %}

{% block content %}
    <div class="container mb-5">
      <div class="row">
        <div class="col-12">
          <div class="card-deck">
            {% for clinic in clinic %}
            <div class="card">
              <img src="{{ clinic.feature_image.url }}" class="card-img-top" alt="Clinic Image" style="object-fit: cover; height: 200px;">
              <div class="card-body">
                <h5 class="card-title">{{ clinic.name }}</h5>
                <p class="card-text">{{ clinic.description }}</p>
              </div>
              <div class="card-footer">
                <a href="{% url 'main_app:clinics_detail' clinic.id %}" class="btn btn-primary">View More</a>
              </div>
            </div>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
    
{% endblock %}

Hospital/main_app/templates/main_app/manager.html
{% extends 'main_app/base.html' %}
{% load static %}

{% block content %}
<div class="container mb-3">
    <h2>Clinics</h2>
    <div class="mb-5">
        <a href="{% url 'main_app:clinics' %}" class="btn btn-primary">Clinics</a>
        <a href="{% url 'main_app:manager_add' %}" class="btn btn-primary">Add Clinic</a>
    </div>
    <h2>Appointments</h2>
    <div class="container mb-3">
        <a href="{% url 'main_app:manager_appointments' %}" class="btn btn-primary">Appointments</a>
        <a href="{% url 'main_app:appointments_add' %}" class="btn btn-primary">Add Appointment</a>
    </div>
</div>
{% endblock %}

Hospital/main_app/templates/main_app/not_found.html
{% extends 'main_app/index.html' %}

{% block title %} Not Found {% endblock%}


{% block content %}

<div class="d-flex align-items-center justify-content-center vh-100">
    <div class="text-center">
        <h1 class="display-1 fw-bold">404</h1>
        <p class="fs-3"> <span class="text-danger">Opps!</span> not found.</p>
        <p class="lead">
            This Clinic not Longer Available.
        </p>
        <a href="{% url 'main_app:index_page' %}" class="btn btn-primary">Go Home</a>
    </div>
</div>

{% endblock %}

Hospital/main_app/templates/main_app/search.html
{% extends 'main_app/base.html' %}
{% load static %}

{% block content %}
    <div class="container col-xxl-8 px-4 py-5">
        <nav class="navbar">
            <div class="container-fluid">
                <form action="{% url 'main_app:search' %}" method="GET" class="d-flex" role="search">
                    <input name="search" class="form-control me-2" type="search" placeholder="Clinics" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
          </nav>
    </div>

    <div class="container col-xxl-8 px-4 py-5 mb-5">
        <h3>Search results for <span class="text-success">{{request.GET.search}}</span></h3>
        <div class="container col-xxl-8 px-4 py-5 mb-5">
          <div class="row">
            <div class="col-12">
              <div class="card-deck">
                {% for clinic in clinic %}
                <div class="card">
                  <img src="{{ clinic.feature_image.url }}" class="card-img-top" alt="Clinic Image" style="object-fit: cover; height: 200px;">
                  <div class="card-body">
                    <h5 class="card-title">{{ clinic.name }}</h5>
                    <p class="card-text">{{ clinic.description }}</p>
                  </div>
                  <div class="card-footer">
                    <a href="{% url 'main_app:clinics_detail' clinic.id %}" class="btn btn-primary">View More</a>
                    {% if request.user.is_staff %}
                        <a href="{% url 'main_app:manager_update' clinic.id %} " class="btn btn-warning">Update</a>
                    {% endif %}
                  </div>
                </div>
                {% endfor %}
              </div>
            </div>
          </div>
        </div>
  </div>
{% endblock %}