HospitalWebsite/HospitalWebsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings 


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main_app.urls")),
    path('accounts/', include("accounts.urls"))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

HospitalWebsite/main_app/urls.py
from django.urls import path
from . import views

app_name = "main_app"

urlpatterns = [
    path("", views.index_page, name="index_page"),
    path("clinic/add/", views.add_update_clinic, name="add_update_clinic"),
    path("clinic/detail/<clinic_id>/", views.detail, name="detail"),
    path("clinic/search/", views.search, name="search"),
    path("clinic/update/<clinic_id>/", views.update_clinic, name="update_clinic"),
    path("clinic/view_appointment/<clinic_id>/", views.view_appointment, name="view_appointment"),
    path("clinic/delete/<appointment_id>/", views.delete_appointment, name="delete_appointment"),

    path("clinic/<clinic_id>/book/add/", views.book_appointment, name="book_appointment"),
    path("clinic/search/", views.search, name="search"),
]

HospitalWebsite/main_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

### Models
class Clinic(models.Model):
    CHOICES = (
        ('Heart Center', 'Heart Center'),
        ('Neuroscience Center', 'Neuroscience Center'),
        ('Obesity Center', 'Obesity Center'),
        ('Eye Center', 'Eye Center'),
        ('Orthopedic Center', 'Orthopedic Center'),
        ('Pediatric Center', 'Pediatric Center')
    )
    name=models.CharField(max_length=200)
    feature_image=models.ImageField(upload_to="images/", default="images/default.jpg")
    description=models.TextField()
    department= models.CharField(max_length=50,choices=CHOICES,default="null")
    established_at=models.DateField()
    
    def __str__(self) -> str:
        return f"{self.name}"


class Appointment(models.Model):
        clinic = models.ForeignKey(Clinic, on_delete=models.CASCADE)
        user = models.ForeignKey(User, on_delete=models.CASCADE)
        case_description=models.TextField()
        patient_age=models.IntegerField()
        appointment_datetime=models.DateTimeField()
        is_attended=models.BooleanField(default=False)

        def __str__(self) -> str:
            return f"{self.user.username} on {self.clinic}"

HospitalWebsite/main_app/views.py
from django.shortcuts import render ,redirect
from django.http import HttpRequest, HttpResponse 
from .models import Clinic, Appointment
# Create your views here.

def index_page(request: HttpRequest):

    clinics = Clinic.objects.all()

    return render(request, "main_app/index.html", {"clinics":clinics})

def add_update_clinic(request:HttpRequest):
    if not (request.user.is_staff and request.user.has_perm("main_app.add_update_clinic")):
        return redirect("users_app:no_permission_page")
    

    if request.method == "POST":

        new_clinic = Clinic(name=request.POST["name"], feature_image=request.FILES["feature_image"],
                         description=request.POST["description"],department = request.POST["department"], established_at=request.POST["established_at"])
        new_clinic.save()
        return redirect("main_app:index_page")

    return render(request, "main_app/add_update_clinic.html")

def detail(request:HttpRequest, clinic_id):

    try:
        clinic = Clinic.objects.get(id=clinic_id)
    except:
        return render(request, 'main_app/not_found.html')

    return render(request, 'main_app/detail.html', {"clinic" : clinic})

def search(request:HttpRequest):
    search_phrase = request.GET.get("search", "")
    clinics = Clinic.objects.filter(name__contains=search_phrase)

    return render(request, "main_app/search.html", {"clinics" : clinics})

def update_clinic(request:HttpRequest, clinic_id):

    clinic = Clinic.objects.get(id=clinic_id)
    iso_date = clinic.established_at.isoformat()
    if request.method == "POST":
        clinic.name = request.POST["name"]
        clinic.description = request.POST["description"]
        clinic.established_at = request.POST["established_at"]

        if "feature_image" in request.FILES:
            clinic.feature_image = request.FILES["feature_image"]
        clinic.save()

        return redirect("main_app:detail", clinic_id=clinic.id)

    return render(request, 'main_app/update_clinic.html', {"clinic" : clinic, "iso_date" : iso_date})

def book_appointment(request:HttpRequest, clinic_id):

    if request.method == "POST":
        clinic_object = Clinic.objects.get(id=clinic_id)
        new_appointment = Appointment(clinic=clinic_object, user=request.user, case_description=request.POST["case_description"], patient_age=request.POST["patient_age"],
                                      appointment_datetime=request.POST["appointment_datetime"])
        new_appointment.save()

    return redirect("main_app:detail", clinic_id=clinic_id)

def view_appointment(request:HttpRequest, clinic_id):

    try:
        clinic = Clinic.objects.get(id=clinic_id)
        appointments = Appointment.objects.filter(clinic=clinic)
    except:
        return render(request, 'main_app/not_found.html')

    return render(request, 'main_app/view_appointment.html', {"clinic" : clinic, "appointments" : appointments})





def delete_appointment(request:HttpRequest, appointment_id):
    if not (request.user.is_staff and request.user.has_perm("main_app.add_update_clinic")):
        return redirect("users_app:no_permission_page")
    
    appointment = Appointment.objects.get(id=appointment_id)

    appointment.delete()

    return redirect("main_app:index_page")

HospitalWebsite/accounts/templates/accounts/log_in.html
{% extends 'main_app/base.html'%}
{% load static%}
{% block title %}
Log In
{% endblock %}


{% block content %}
<section id="contact">
    <div class="container">
        <div class="row">
            <div class="col-12" data-aos="fade-up">
                <div class="intro text-center">
                    <div class="hr-line"></div>
                        <h1 class="diisplay-4">LogIn </h1>
                        <p class="mx-auto">please fill in the required fields.</p>
                </div>
            </div>
        </div>
      
        <div class="row">
            <div class="col-lg-8 mx-auto">
                {% if msg %}
                     <p class="text-danger">{{msg}}</p>
                 {% endif %}
                <form action="{% url 'accounts:log_in' %}" method="post" class="row gy-3">
                    {% csrf_token %}

                     <div class="col-lg-6">
<!--INPUT-->               <input name="username" type="text" id="floatingInput" class="form-control" placeholder="User name">
                    </div>
                    <div class="col-lg-12">
<!--INPUT-->               <input type="password" class="form-control" id="floatingPassword" placeholder="Password" name="password">
                    </div>
                    <div class="col-12">
<!--button-->              <button class="btn btn-dark">LogIn</button>
                            <p class="mt-5 mb-3 text-body-secondary">© 2017–2023</p>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>


{% endblock %}

HospitalWebsite/accounts/templates/accounts/no_permission.html
{% extends 'main_app/base.html'%}
{% load static%}
{% block title %}
No Permission Page
{% endblock %}


{% block content %}
<section id="contact">
    <div class="container">
        <div class="row">
            <div class="col-12" data-aos="fade-up">
                <div class="intro text-center">
                    <div class="hr-line"></div>
                        <h1 class="diisplay-4">You don't have permission. Please <span><a href="{% url 'accounts:log_in' %}">Log In</a> </span> with another user</h1>
                        <p class="mx-auto"><a href="{% url 'main_app:home_page' %}"><button class="btn btn-dark">Back</button></a></p>
                </div>
            </div>
        </div>

            </div>
        </div>
    </div>
</section>


{% endblock %}

HospitalWebsite/accounts/templates/accounts/no_premission.html
{% extends 'main_app/base.html'%}


{% block title %} Sign Up new user {% endblock %}

{% block content %}

<div class="text-danger">
    <h2>You don't have permission. Please sign with another user</h2>
</div>

{% endblock %}

HospitalWebsite/accounts/templates/accounts/register.html
{% extends 'main_app/base.html'%}
{% load static%}
{% block title %}
Register
{% endblock %}


{% block content %}
<section id="contact">
    <div class="container">
        <div class="row">
            <div class="col-12" data-aos="fade-up">
                <div class="intro text-center">
                    <div class="hr-line"></div>
                        <h1 class="diisplay-4">Register </h1>
                        <p class="mx-auto">please fill in the required fields.</p>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-8 mx-auto">            
                {% if msg %}
                <div class="alert alert-danger" role="alert">
                    {{msg}}
                </div>
                {% endif %}
                <form action="{% url 'accounts:register' %}" method="post" class="row gy-3">
                    {% csrf_token %}
                    <div class="col-lg-6">
<!--INPUT-->               <input type="text" class="form-control" id="floatingInput" placeholder="First name" name="first_name">
                    </div>
                    <div class="col-lg-6">
<!--INPUT-->               <input type="text" class="form-control" id="floatingInput" placeholder="Last name" name="last_name">
                    </div>
                     <div class="col-lg-6">
<!--INPUT-->               <input name="username" type="text" id="floatingInput" class="form-control" placeholder="User name">
                    </div>
                    <div class="col-lg-6">
<!--INPUT-->               <input name="email" type="email" id="floatingInput" class="form-control" placeholder="Email">
                    </div>
                    <div class="col-lg-12">
<!--INPUT-->               <input type="password" class="form-control" id="floatingPassword" placeholder="Password" name="password">
                    </div>
                    <div class="col-12">
<!--button-->              <button class="btn btn-dark">Register</button>
                            <p class="mt-5 mb-3 text-body-secondary">© 2017–2023</p>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>


{% endblock %}

HospitalWebsite/accounts/templates/accounts/signin.html
{% extends 'main_app/base.html'%}


{% block title %} Sign Up new user {% endblock %}

{% block content %}
<div class="container d-flex flex-column justify-content-center align-items-center">

    <h2>Sign In</h2>
    {% if msg %}
        <p class="text-danger">{{msg}}</p>
    {% endif %}
    <form class="d-flex flex-column gap-3 w-50" action="{% url 'accounts:sign_in' %}" method="POST">
        {% csrf_token %}
        

        <div class="form-floating">
            <input type="text" class="form-control" id="floatingInput" placeholder="username" name="username">
            <label for="floatingInput">User name</label>
        </div>


        <div class="form-floating">
          <input type="password" class="form-control" id="floatingPassword" placeholder="Password" name="password">
          <label for="floatingPassword">Password</label>
        </div>
    

        <button class="btn btn-primary w-100 py-2" type="submit">Sign In</button>
        <p class="mt-5 mb-3 text-body-secondary">© 2017–2023</p>
      </form>
    </div>

{% endblock %}

HospitalWebsite/accounts/templates/accounts/signup.html
{% extends 'main_app/base.html'%}


{% block title %} Sign Up new user {% endblock %}

{% block content %}
<div class="container d-flex flex-column justify-content-center align-items-center">

    <h2>Sign Up</h2>
    {% if msg %}
    <div class="alert alert-danger" role="alert">
        {{msg}}
    </div>
    {% endif %}
    <form class="d-flex flex-column gap-3 w-50" action="{% url 'accounts:sign_up' %}" method="POST">
        {% csrf_token %}


        <div class="form-floating">
            <input type="email" class="form-control" id="floatingInput" placeholder="name@example.com" name="email">
            <label for="floatingInput">Email address</label>
        </div>

        <div class="form-floating">
            <input type="text" class="form-control" id="floatingInput" placeholder="username" name="username">
            <label for="floatingInput">User name</label>
        </div>

        <div class="form-floating">
            <input type="text" class="form-control" id="floatingInput" placeholder="First name" name="first_name">
            <label for="floatingInput">First name</label>
        </div>

        <div class="form-floating">
            <input type="text" class="form-control" id="floatingInput" placeholder="Last name" name="last_name">
            <label for="floatingInput">Last name</label>
        </div>

        <div class="form-floating">
            <input type="password" class="form-control" id="floatingPassword" placeholder="Password" name="password">
            <label for="floatingPassword">Password</label>
        </div>


        <button class="btn btn-primary w-100 py-2" type="submit">Sign up</button>
        <p class="mt-5 mb-3 text-body-secondary">© 2017–2023</p>
    </form>
</div>

{% endblock %}

HospitalWebsite/main_app/templates/main_app/about_us.html
{% extends 'main_app/base.html'%}
{% load static%}
{% block title %}
About Us
{% endblock %}
{% block header %}
<style>
.aboutMe{
    background-color:  #2d4d6910;
    display: flex;
    flex-direction: column;
    row-gap: 40px;
    font-family: 'Ysabeau', sans-serif;
    font-family: 'Indie Flower', cursive;
}
</style>
{% endblock %}

{% block content %}
<section class="aboutMe">
    <div class="container">
        <div class="row gy-4">
            <div class="col-12" data-aos="fade-up">
                <div class="intro text-center">
                    <div class="hr-line"></div>
                        <h1 style="font-size: 40pt;color: rgb(35, 61, 84);" class="diisplay-4">About ND. Hospital</h1>
                        <p class="mx-auto"> </p>
                        <hr>
                </div>
            </div>
        </div>
        <br>
        <div class="row  align-items-center">
            <div class="col-lg-6 offset-1">
                <p><span style="color: rgb(35, 61, 84);font-size: larger;">ND. Hospital/span> is a leading healthcare provider dedicated to serving the community with the highest level of care and compassion. Founded in 1990, our hospital has been at the forefront of medical innovation and excellence for over 30 years. Our team of highly trained healthcare professionals is committed to providing personalized care to every patient, treating not just their medical needs but also their emotional and psychological well-being. Our state-of-the-art facilities and advanced medical technology enable us to diagnose and treat a wide range of medical conditions, from routine check-ups to complex surgeries. At ND Hospital, we believe that healthcare is a fundamental human right, and we are committed to making quality healthcare accessible to all. We are proud to be a part of the community and to serve our patients with the utmost care and respect.</p>

            </div>
            <div class="col-lg-3 offset-1">
                <img style="width: 100%;height: 50%;border-radius: 20px; object-fit: cover; border: 8px solid #060606;box-shadow: 0 5px 10px rgba(0, 0, 0, 0.358);" src="{% static 'images/logoo1.png' %}" alt="">
            </div>
        </div>
        <br><br>        
        
        </div>
</section>


{% endblock %}

HospitalWebsite/main_app/templates/main_app/add_clinics.html
{% extends 'main_app/base.html'%}
{% load static%}
{% block title %}
Add Clinics
{% endblock %}


{% block content %}
<section id="contact">
    <div class="container">
        <div class="row">
            <div class="col-12" data-aos="fade-up">
                <div class="intro text-center">
                    <div class="hr-line"></div>
                        <h1 class="diisplay-4">Add Clinics</h1>
                        <p class="mx-auto"> </p>
                </div>
            </div>
        </div>
        <div class="row ">
            <div class="col-lg-8 mx-auto">
                <form action="{% url 'main_app:add_clinics' %}" method="post" class="row gy-3" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="col-lg-6">
<!--INPUT-->               <input type="text" class="form-control" placeholder="Name" name="name">
                    </div>
                    <div class="col-lg-6">
                        <select class="form-select" aria-label="Default select example" name="department" required="" min-length="1">
                            <option value="">Select department</option>
                            {% for choice in department_choices %}
                            <option value="{{ choice.0 }}">{{ choice.1 }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    
                    <div class="col-lg-12">
<!--INPUT-->               <textarea class="form-control" placeholder="Description" name="description" ></textarea>
                    </div>
                    <div class="col-lg-12">
<!--INPUT-->               <input type="date" class="form-control" placeholder="Established at" name="established_at">
                    </div>
                    <div class="col-lg-12">
                        <label for="inputZip" class="form-label">Upload feature image</label>
                        <input type="file" name="feature_image" class="form-control" id="inputZip" >
                    </div>
                    <div class="col-12">
<!--button-->              <button class="btn btn-dark">Add clinics</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>

{% endblock %}

HospitalWebsite/main_app/templates/main_app/appointment_list.html
{% extends 'main_app/base.html'%}
{% load static%}
{% block title %}
Appointments
{% endblock %}
{% block header %}
<style>
    .__cards{
    margin: 10px;
    padding: 10px;
    padding-left: 50px;
    background-color: #2d4d6910 ;
    overflow: hidden;
    border: 5px solid #060606;;
    border-radius: 20px;
}
</style>
{% endblock %}

{% block content %}


<section class="project__detail">
    <div class="container">
        <div class="row ">
            <div class="col-12 mt-5">
                <div class="intro text-center">
                    <div class="hr-line"></div>
                        <h1 style="font-size: 20pt;" class="diisplay-4">Your<span style="color: #325473;font-size: 30pt;">Appointments</span> </h1>
                        
                        <hr>
                </div>
            </div>
            {% if messages %}
                    <ul style="color:darkgreen;" class="messages">
                        {% for message in messages %}
                            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            {% for appointment in appointment_user%}
            <div class="col--6 " data-aos="fade-up" data-aos-delay="150">
                <div class="__cards">
                            <h4><strong>Patient name</strong>: {{appointment.user.first_name}} {{appointment.user.last_name}}</h4>
                            <p style="font-size: 14pt;display: flex; flex-direction: row; column-gap: 70px;"><span><strong>Clinic name:</strong> : {{ appointment.clinic.name }}</span><span><strong> Department:</strong> {{ appointment.clinic.department }}</span></p>
                            <p ><strong>Case description</strong> : {{appointment.case_description}}</p>
                            <p ><strong>Patient age</strong> : {{appointment.patient_age}}</p>

                            <small class="text-body-secondary"><p style="font-size: 14pt;"><strong>appointment datetime:</strong> : {{appointment.appointment_datetime}}</p></small>
                        {% if request.user.is_staff %}
                            <p ><strong>is attended?</strong> : {{appointment.is_attended}}</p>
                            <a href="{% url 'main_app:update_appointment' appointment.id %}"><button class="btn btn-warning">Update appointment</button></a>
                            <a href="{% url 'main_app:create_appointment' appointment.clinic.id %}"><button class="btn btn-warning">Add appointment</button></a>
                            <a href="{% url 'main_app:delete_appointment' appointment.id %}"><button class="btn btn-warning">delete appointment</button></a>
                            
                        {% endif %}
                       
                    </div>
                </div>
            
            {% endfor %}
            </div>
        </div>
        <hr>

    </div>
</section>


{% endblock %}

HospitalWebsite/main_app/templates/main_app/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Changa&family=Nanum+Gothic&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <link href="{% static 'styles/main.css'%}" rel="stylesheet" />
</head>
  <body>
    
    <div class="container-fluid p-0">
        <header class="p-3 text-bg-dark">
            <div class="container">
                <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start gap-4">
                <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none"><h3 class="p-0 m-0">Hospital</h3></a>
        
                <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                    {% if request.user.is_staff %}
                    <li><a href="{% url 'main_app:add_update_clinic' %}" class="nav-link px-2 text-white">Add Clinic</a></li>
                    {% endif %}
                    <li><a href="#" class="nav-link px-2 text-white">FAQs</a></li>
                    <li><a href="#" class="nav-link px-2 text-white">About</a></li>
                </ul>
                <form action="{% url 'main_app:search' %}" method="GET" class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search">
                    <input type="search" name="search" class="form-control form-control-dark text-bg-dark" placeholder="Search..." aria-label="Search">
                </form>
                
                {% if request.user.is_authenticated %}
                    <div class="d-flex gap-2 align-items-center justify-content-center">
                        <h5 class="m-0 p-0">Welcome {{ request.user.username }}</h5>
                        <a href="{% url 'accounts:log_out' %}" class="btn btn-danger">Log Out</a>
                    </div> 
                {% else %}
                    <div class="text-end">
                        <a  href="{% url 'accounts:sign_in' %}" class="btn btn-outline-light me-2">Sign In</a>
                        <a href="{% url 'accounts:sign_up' %}" class="btn btn-warning">Sign up</a>
                    </div>
                {% endif %}


                </div>
            </div>
            </header>
        
        <div class="container-fluid p-4">
        {% block content%}
        {% endblock %}
        </div>

        <footer class="py-3 my-4">
            <ul class="nav justify-content-center border-bottom pb-3 mb-3">
              <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Home</a></li>
              <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Features</a></li>
              <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Pricing</a></li>
              <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">FAQs</a></li>
              <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">About</a></li>
            </ul>
            <p class="text-center text-body-secondary">© 2023 Company, Inc</p>
        </footer>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
  </body>
</html>

HospitalWebsite/main_app/templates/main_app/book_appointment.html
{% extends 'main_app/base.html' %}

{% block title %} Make Appointment {% endblock%}


{% block content%}
<h1>Make Appointment</h1>
<div class="container">

    <form action="{% url 'main_app:book_appointment' clinic.id %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Name</label>
            <input type="text" class="form-control" id="exampleFormControlInput1" placeholder="fill in name" name="name">
        </div>

        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Patient Age</label>
            <textarea class="form-control" id="exampleFormControlInput1" placeholder="Type Your Age" name="patient_age"></textarea>
        </div>

        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Case Description</label>
            <textarea class="form-control" id="exampleFormControlInput1" placeholder="descripe your problem" name="case_description"></textarea>
        </div>

        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Appointment Time</label>
            <input type="date" name="appointment_datetime" />
        </div>



        <div class="mb-3">
            <input type="submit" value="Book Appointment" class="btn btn-primary" />
        </div>


    </form>

</div>
{% endblock %}

HospitalWebsite/main_app/templates/main_app/detail.html
{% extends 'main_app/base.html' %}

{% block title %}{{clinic.name}}{% endblock%}

{% block content %}

<div class="container d-flex flex-column gap-2">
    <h1>{{clinic.name}}</h1>
    
    <img class="rounded-5" src="{{ clinic.feature_image.url }}" />
    <div class="d-flex justify-content-between align-items-center gap-2">
        <div class="d-flex gap-2">

            {% if request.user.is_staff %}
            <a href="{% url 'main_app:update_clinic' clinic.id %}" class="btn btn-warning">Update Clinic</a>

            {% endif %}

        </div>
    </div>

    <p>{{clinic.description}}</p>
</div>    





<div class="container mt-3">
    <h3>Book Appointment</h3>

    {% if request.user.is_authenticated %}
    <form action="{% url 'main_app:book_appointment' clinic.id %}" method="POST">
        {% csrf_token %}



        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Patient Age</label>
            <input type="number" class="form-control" id="exampleFormControlInput1" placeholder="Type Your Age" name="patient_age">
        </div>

        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Case Description</label>
            <textarea class="form-control" id="exampleFormControlInput1" placeholder="descripe your problem" name="case_description"></textarea>
        </div>

        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Appointment Time</label>
            <input type="datetime-local" name="appointment_datetime" />
        </div>

        <div class="mb-3">
            <input type="submit" value="Book Appointment" class="btn btn-primary" />
            <a href="{% url 'main_app:view_appointment' clinic.id %}" class="btn btn-warning">View Appointment</a>

        </div>

    </form>
    {% else %}
    <div class="alert alert-dark" role="alert">
       Please <a href="{% url 'accounts:sign_in' %}">sign in</a> or <a href="{% url 'accounts:sign_up' %}">sign up</a> to Book an Appointment
      </div>
    {% endif %}

</div>
{% endblock %}

HospitalWebsite/main_app/templates/main_app/update_clinic.html
{% extends 'main_app/base.html' %}

{% block title %} Update Clinic {% endblock%}


{% block content%}
<h1>Update Clinic: {{clinic.name}}</h1>
<div class="container">

    <form action="{% url 'main_app:update_clinic' clinic.id %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}


        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Name</label>
            <input type="text" class="form-control" id="exampleFormControlInput1" placeholder="update the name" name="name" value="{{clinic.name}}">
        </div>

        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Description</label>
            <textarea class="form-control" id="exampleFormControlInput1" placeholder="update in title" name="description">{{clinic.description}}</textarea>
        </div>




        <div class="mb-3 d-flex flex-column gap-2">
            <label for="exampleFormControlInput1" class="form-label">Choose Image</label>
            <img src="{{clinic.feature_image.url}}" class="w-25 rounded-5"/>
            <input type="file" name="image" class="form-control" />
        </div>

        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Established At</label>
            <input type="date" name="established_at" value="{{iso_date}}" />
        </div>

        <div class="mb-3">
            <input type="submit" value="Update Clinic" class="btn btn-primary" />
        </div>


    </form>

</div>
{% endblock %}

HospitalWebsite/main_app/templates/main_app/view_appointment.html
{% extends 'main_app/base.html' %}

{% block title %} View Appointment{% endblock%}


{% block content%}
<div class="container d-flex flex-column gap-3">
    <h2>Appointments</h2>
    {% for appointment in appointments %}

    <div class="d-flex flex-column p-4 border border-1 rounded-5 gap-1">
        <h6>{{appointment.user.username}}</h6>
        <h6>Patient Age: {{appointment.patient_age}}</h6>
        <p>{{appointment.appointment_datetime}}</p>
        <p>{{appointment.case_description}}</p>
    </div>

    <div class="d-flex gap-2">
        {% if request.user.is_staff %}
        <a href="{% url 'main_app:delete_appointment' appointment_id=appointment.id   %}" class="btn btn-danger">Delete Appointment</a>
        {% endif %}

    </div>
    
    {% endfor %}

</div>
{% endblock %}