Hospital/Hospital/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('', include('clinic_app.urls')),
    path("admin/", admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Hospital/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('signin/', views.signin, name="sign_in"),
    path('signup/', views.signup, name="signup"),
    path('user/logout/', views.logout_view, name="log_out"),
]

Hospital/clinic_app/urls.py
from django.urls import path
from . import views

app_name = "clinic_app"

urlpatterns = [
    path("", views.home, name = "home"),
    path('add/clinic', views.add_clinic, name='add_clinic'),
    path('clinic/details/<clinic_id>/', views.clinic_details, name='clinic_details'),
    path("search/", views.search, name="search"),
    path("update/clinic/<clinic_id>/", views.update_clinic, name="update_clinic"),
    path("contact/", views.contact, name="contact"),
    path("appointment/<clinic_id>/", views.appointment_page, name="appointment"),
    path('create/appointment/<clinic_id>/', views.create_appointment, name='create_appointment'),
    path('not/found/', views.not_found, name="not_found"),
    path('update/appointment/<appointment_id>', views.update_appointment, name="update_appointment"),
    path('delete/appointment/<appointment_id>', views.delete_appointment, name="delete_appointment"),

]

Hospital/clinic_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Clinic(models.Model):
    name = models.CharField(max_length=100)
    feature_image = models.ImageField(upload_to="images/", default="images/default.png")
    description = models.TextField()
    DEPARTMENT_CHOICES = [
        ('Heart Center', 'Heart Center'),
        ('Neuroscience Center', 'Neuroscience Center'),
        ('Obesity Center', 'Obesity Center'),
        ('Eye Center', 'Eye Center'),
        ('Orthopedic Center', 'Orthopedic Center'),
        ('Pediatric Center', 'Pediatric Center'),
    ]
    
    department = models.CharField(max_length=50, choices=DEPARTMENT_CHOICES)
    established_at = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.name
    
class Appointment(models.Model):
    clinic = models.ForeignKey(Clinic, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    case_description = models.TextField()
    patient_age = models.PositiveIntegerField()
    appointment_datetime = models.DateTimeField()
    is_attended = models.BooleanField(default = False)

    def __str__(self):
        return f"{self.user.username}'s appointment at {self.clinic.name}"

Hospital/clinic_app/views.py
from django.shortcuts import render, redirect
from .models import Clinic, Appointment
from django.http import HttpRequest
from django.contrib.auth.models import User

# Create your views here.

def home(request):
    clinics = Clinic.objects.all()
    return render(request, 'clinic_app/home.html', {'clinics':clinics})

def add_clinic(request:HttpRequest):
    #check
    if not request.user.is_staff:
        return redirect("clinic_app:not_found")
    # add
    if request.method == 'POST':
        cname = request.POST['name']
        cdescription = request.POST["description"]
        cdepartment = request.POST["department"]
        cestablished_at = request.POST["established_at"]
        new_clinic = Clinic(name=cname, description=cdescription, department=cdepartment, established_at=cestablished_at)
        if "feature_image" in request.FILES:
            new_clinic.feature_image = request.FILES['feature_image']
        new_clinic.save()
        return redirect('clinic_app:home') 
    else: 
        return render(request, 'clinic_app/add_clinic.html')
    
def clinic_details(request:HttpRequest, clinic_id):
    clinic = Clinic.objects.get(id=clinic_id)
    try:
        if request.method == "POST":
            pass 
    except:
        return render(request, 'clinic_app/no_clinic.html')
    return render(request, 'clinic_app/clinic_details.html', {"clinic":clinic})

def search(request:HttpRequest):
    search_results = request.GET.get("search", "")
    clinic = Clinic.objects.filter(name__contains=search_results)
    return render(request, "clinic_app/search.html", {"clinics":clinic})

def update_clinic(request:HttpRequest, clinic_id):
    #check
    if not request.user.is_staff:
        return redirect("clinic_app:not_found")
    #update
    clinic = Clinic.objects.get(id=clinic_id)
    if request.method == "POST":
        clinic.name = request.POST['name']
        clinic.feature_image = request.FILES['feature_image']
        clinic.description = request.POST["description"]
        clinic.department = request.POST["department"]
        clinic.established_at = request.POST["established_at"]
        clinic.save()
        return redirect("clinic_app:clinic_details", clinic_id=clinic.id)
    else:
        return render(request, 'clinic_app/update_clinic.html', {"clinic":clinic})
    
def contact(request):
    return render(request, 'clinic_app/contact.html')

def appointment_page(request:HttpRequest, clinic_id):
    clinic = Clinic.objects.get(id=clinic_id)
    appointments = Appointment.objects.filter(clinic=clinic).order_by('appointment_datetime')
    return render(request, 'clinic_app/appointment.html', {'clinic': clinic, 'appointments':appointments})

def create_appointment(request:HttpRequest, clinic_id):
    clinic = Clinic.objects.get(id=clinic_id)
    if request.method == 'POST':
        Acase_description = request.POST['case_description']
        Apatient_age = request.POST['patient_age']
        Aappointment_datetime = request.POST["appointment_datetime"]
        new_appointment = Appointment(user=request.user, clinic=clinic, case_description=Acase_description, patient_age=Apatient_age, appointment_datetime=Aappointment_datetime)
        new_appointment.save()
        return redirect('clinic_app:appointment', clinic_id=clinic.id)
    return render(request, 'clinic_app/create_appointment.html', {"clinic":clinic})

def not_found(request):
    return render(request, 'clinic_app/not_found.html')

def update_appointment(request:HttpRequest, appointment_id):
    #check
    if not request.user.is_staff:
        return redirect("clinic_app:not_found")
    #update
    appointment = Appointment.objects.get(id=appointment_id)
    if request.method == "POST":
        appointment.case_description = request.POST["case_description"]
        appointment.patient_age = request.POST["patient_age"]
        appointment.appointment_datetime = request.POST["appointment_datetime"]
        appointment.is_attended = request.POST["is_attended"]
        appointment.save()
        return redirect("clinic_app:appointment", clinic_id=appointment.clinic.id)
    return render(request, 'clinic_app/update_appoinment.html', {'appointment':appointment})

def delete_appointment(request:HttpRequest, appointment_id):
    #check
    if not request.user.is_staff:
        return redirect("clinic_app:not_found")
    #delete
    appointment = Appointment.objects.get(id=appointment_id)
    appointment.delete()
    return redirect("clinic_app:appointment", clinic_id=appointment.clinic.id)

Hospital/clinic_app/templates/clinic_app/add_clinic.html
{% extends 'clinic_app/base.html' %}
{% block title %} Add Clinic {% endblock %}

{% block content %}

<h1 style="text-align: center">Add Clinic</h1>

<form method="POST" style="text-align: center" enctype="multipart/form-data">
    {% csrf_token %}
    <div>
        <label>enter clinic name</label><br>
        <input placeholder="clinic name" name="name" type="text">
    </div>
    <br>
    <div>
        <label>enter clinic description</label><br>
        <textarea placeholder="description" name="description"></textarea>
    </div>
    <br>
    <div>
        <label>enter clinic image</label><br>
        <input type="file" name="feature_image" />
    </div>
    <br>
    <label>enter clinic department</label><br>
    <div>
        <select name="department">
            <option value="Heart Center">Heart Center</option>
            <option value="Neuroscience Center">Neuroscience Center</option>
            <option value="Obesity Center">Obesity Center</option>
            <option value="Eye Center">Eye Center</option>
            <option value="Orthopedic Center">Orthopedic Center</option>
            <option value="Pediatric Center">Pediatric Center</option>
        </select>
    </div>
    <br>
    <div>
        <label>enter clinic established date</label><br>
        <input type="date" name="established_at">
    </div>
    <br>
    <button type="submit">Add clinic</button>
</form>
<br>

{% endblock %}

Hospital/clinic_app/templates/clinic_app/appointment.html
{% extends 'clinic_app/base.html' %}
{% block title %} Appointments {% endblock%}

{% block content %}

{% if request.user.is_authenticated %}
<h1>{{ clinic.name }}, appointment schedule</h1>
<table>
    <thead>
        <tr>
            <th style="text-align: center">Date/Time</th>
            <th style="text-align: center">Case Description</th>
            <th style="text-align: center">Patient Age</th>
            <th style="text-align: center">Attended</th>
        </tr>
    </thead>
    <tbody>
        {% for appointment in appointments %}
        <tr>
            <td style="text-align: center">{{ appointment.appointment_datetime }}</td>
            <td style="text-align: center">{{ appointment.case_description }}</td>
            <td style="text-align: center">{{ appointment.patient_age }}</td>
            <td style="text-align: center">{% if appointment.is_attended %}Yes{% else %}No{% endif %}</td>
        </tr>
        {% if request.user.is_staff %}
        <td style="text-align: center">
            <label>update:</label>
            <a href="{%url 'clinic_app:update_appointment' appointment.id %}">update</a>
            <label>delete:</label>
            <a href="{%url 'clinic_app:delete_appointment' appointment.id %}">delete</a>
        </td>
        {% endif %}
        {% empty %}
        <tr>
            <td style="text-align: center" colspan="4">No appointments scheduled.</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% else %}
<br>
<div style="text-align: center"><a href="{% url 'accounts:sign_in' %}">sign in</a> or <a
        href="{% url 'accounts:signup' %}">sign up</a> to book and browse appointments</div>
{% endif %}

<br>

{% if request.user.is_authenticated %}
<h1 style="text-align: center">Create Appointment</h1>

<form action="{% url 'clinic_app:create_appointment' clinic.id %}" method="POST" style="text-align: center">
    {% csrf_token %}
    <div>
        <label>enter your date and time</label><br>
        <input placeholder="date" name="appointment_datetime" type="datetime-local">
    </div>
    <br>
    <div>
        <label>enter your age</label><br>
        <input placeholder="age" name="patient_age" type="number">
    </div>
    <br>
    <div>
        <label>enter your case description</label><br>
        <textarea placeholder="description" name="case_description"></textarea>
    </div>
    <br>
    <button type="submit">Add appointment</button>
</form>
{% endif %}

<br>

{% endblock %}

Hospital/clinic_app/templates/clinic_app/base.html
<!DOCTYPE html>
{% load static %}

<html>

<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
    <!-- Latest compiled and minified CSS -->
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static '/css/styles.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>

<body>

    <div id="w">
        <header id="topbar" class="clearfix">
            <div id="logo">ClinicWebsite</div>

            <nav id="topnav">
                <ul>
                    <li><a href="{% url 'clinic_app:home' %}">Home</a></li>
                    <li><a href="{% url 'clinic_app:contact' %}">Contact</a></li>
                    {% if request.user.is_authenticated %}
                    <li><a href="{% url 'accounts:log_out' %}">Log out</a></li>
                    {% else %}
                    <li><a href="{% url 'accounts:sign_in' %}">Sign in</a></li>
                    <li><a href="{% url 'accounts:signup' %}">Sign up</a></li>
                    {% endif %}
                </ul>
            </nav>
        </header>

        <div id="searchbar" class="clearfix">
            <form action="{% url 'clinic_app:search' %}" method="GET" id="searchform">
                <input type="search" name="search" id="s"  minlength="4" placeholder="Search keywords..." autocomplete="off">
            </form>
        </div>

        <section id="fullimg"></section>

        <div id="content">
            <p><a href="https://unsplash.com/photos/U4FyCp3-KzY" target="_blank">original image source</a></p>
            <h1>Clinic</h1>
            <p>Clinic that provides various clinical specialties, with a focus on delivering an outstanding patient
                experience.</p>
        </div>

        {% block content%}
        {% endblock %}

        <br><br><footer style="text-align: center"> Copyright &copy; 2023 </footer>
    </div>
</body>

</html>

Hospital/clinic_app/templates/clinic_app/clinic_details.html
{% extends 'clinic_app/base.html' %}
{% block title %} Clinic Details {% endblock%}

{% block content %}

<div style="text-align: center">
    <h1 style="text-align: center">Clinic Details</h1>

    <div style="text-align: center">
        <h4 style="color: orangered">{{ clinic.name }}</h4>
        <label>Description</label><br>
        <p>{{ clinic.description }}</p>
        <label>Department</label><br>
        <p>{{ clinic.department }}</p>
        <label>Established at</label><br>
        <p>{{ clinic.established_at }}</p>
    </div>

    <div>
        {% if request.user.is_staff %}
        <a href="{% url 'clinic_app:update_clinic' clinic.id %}">Update clinic</a><br>
        {% endif %}
        <a href="{% url 'clinic_app:appointment' clinic.id %}">Browse appointments</a><br>
    </div>
</div>

{% endblock %}

Hospital/clinic_app/templates/clinic_app/contact.html
{% extends 'clinic_app/base.html' %}
{% block title %} Contact {% endblock %}

{% block content %}
<h1 style="text-align: center">Contact</h1>

{% endblock %}

Hospital/clinic_app/templates/clinic_app/home.html
{% extends 'clinic_app/base.html' %}
{% block title %} Home {% endblock %}

{% block content %}

<h1 style="text-align: center">Available Clinics</h1>

{% if request.user.is_staff %}
<div style="text-align: center; font-size: 150%;">
    <a href="{% url 'clinic_app:add_clinic' %}">Add new clinic</a>
</div>
{% endif %}

<div style="text-align: center">
    {% for clinic in clinics %}
    <br>
    <h4 style="color: orangered">{{ clinic.name }}</h4>
    <img src="{{ clinic.feature_image.url }}"/>
    <br>
    <label>Description</label><br>
    <p>{{ clinic.description }}</p>
    <label>Department</label><br>
    <p>{{ clinic.department }}</p>
    <label>Established at:</label><br>
    <p>{{ clinic.established_at }}</p>
    <div>
        <a href="{% url 'clinic_app:clinic_details' clinic.id %}">details</a>
    </div>
    {% endfor %}
</div>

{% endblock %}

Hospital/clinic_app/templates/clinic_app/no_clinic.html
{% extends 'clinic_app/base.html' %}
{% block title %} Not Found{ % endblock %}

{% block content %}

  <h1 style="text-align: center">page not found</h1>

{% endblock %}

Hospital/clinic_app/templates/clinic_app/not_found.html
{% extends 'clinic_app/base.html' %}
{% block title %} Not Found {% endblock %}

{% block content %}

  <h1 style="text-align: center">page not found</h1>

{% endblock %}

Hospital/clinic_app/templates/clinic_app/search.html
{%extends 'clinic_app/base.html'%}
{% block title %} Search {% endblock%}

{% block content%}
<h1 style="text-align: center">Search Results</h1>

{% for clinic in clinics %}
<div style="text-align: center">
    <h4 style="color: orangered"> {{ clinic.name }}</h4>
    <a href="{% url 'clinic_app:clinic_details' clinic.id %}">Read more</a>
</div>
{% endfor %}

{% endblock %}

Hospital/clinic_app/templates/clinic_app/update_appoinment.html
{% extends 'clinic_app/base.html' %}
{% block title %} Update appointment {% endblock%}

{% block content %}
<h1 style="text-align: center">Update Appointment</h1>

<div style="text-align: center">
    <label>patient name</label><br>
    <p>{{ appointment.user.username }}</p>
    <label>clinic name</label><br>
    <p> {{ appointment.clinic.name }}</p>
</div>

<hr>

{% if request.user.is_staff %}
<form  method="POST" style="text-align: center">
    {% csrf_token %}
    <div>
        <label>enter your date and time</label><br>
        <input placeholder={{appointment.appointment_datetime}} name="appointment_datetime" type="datetime-local">
    </div>
    <br>
    <div>
        <label>enter your age</label><br>
        <input placeholder={{appointment.patient_age}} name="patient_age" type="number">
    </div>
    <br>
    <div>
        <label>enter your case description</label><br>
        <textarea placeholder="description" name="case_description">{{ appointment.case_description }}</textarea>
    </div>
    <br>
    <div>
        <label>attendedance</label><br>
        <select name="is_attended">
            <option value="True" {% if appointment.is_attended %} selected {% endif %}>Yes</option>
            <option value="False" {% if not appointment.is_attended %} selected {% endif %}>No</option>
        </select>
    </div>
    <br>
    <button type="submit">Save updates</button>
</form>
{% endif %}

{% endblock %}

Hospital/clinic_app/templates/clinic_app/update_clinic.html
{% extends 'clinic_app/base.html' %}
{% block title %} Update clinic {% endblock%}

{% block content%}
<h1 style="text-align: center">Update Clinic</h1>

<div style="text-align: center">
    <form action="{% url 'clinic_app:update_clinic' clinic.id %}" method="POST" style="text-align: center">
        {% csrf_token %}
        <div>
            <input placeholder="clinic name" name="name" type="text">
        </div>
        <br>
        <div>
            <textarea placeholder="description" name="description"></textarea>
        </div>
        <br>
        <div>
            <input type="file" name="feature_image">
        </div>
        <br>
        <div>
            <select name="department">
                <option value="Heart Center">Heart Center</option>
                <option value="Neuroscience Center">Neuroscience Center</option>
                <option value="Obesity Center">Obesity Center</option>
                <option value="Eye Center">Eye Center</option>
                <option value="Orthopedic Center">Orthopedic Center</option>
                <option value="Pediatric Center">Pediatric Center</option>
            </select>
        </div>
        <br>
        <div>
            <input type="date" name="established_at">
        </div>
        <br>
        <button type="submit">Save updates</button>
    </form>
    <br><br>

</div>

{% endblock %}